# Generated by Django 3.2.15 on 2023-11-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciao', '0002_abstractuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='user/foto'),
        ),
    ]
