# Generated by Django 3.2.15 on 2023-11-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciao', '0003_alter_abstractuser_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciao.abstractuser'),
        ),
    ]
